package com.example.usergui_v1.model;

public class ClientModel {
    //TODO GESTIRE L'INVIO AL SERVER DELLE MAIL
    //TODO GESTIRE LE CONDIZIONI DI CONTROLLO DELLE MAIL
    //TODO CAPIRE QUALI METODI SPOSTARE QUI
    //TODO GESTIRE ARRIVO DELLE MAIL
    //TODO GESTIONE ID DELLE MAIL
    //TODO CAPIRE COME FARE AD AVERE I DIVERSI CLIENT

}
